use std::path::Path;

pub const ICON_DIR: &str = "";
pub const ICON_FILE: &str = "";
pub const ICON_EXEC: &str = "";
pub const ICON_LINK: &str = "";

pub fn file_icon(path: &Path) -> &'static str {
    let name = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();

    match name.as_str() {
        "dockerfile" | "docker-compose.yml" | "docker-compose.yaml" => "",
        "makefile" | "gnumakefile" | "cmakelists.txt" => "",
        "vagrantfile" => "",
        "rakefile" | "gemfile" => "",
        "procfile" => "",
        "license" | "licence" | "copying" => "",
        n if n.starts_with("license.") || n.starts_with("licence.") => "",
        "readme" => "",
        n if n.starts_with("readme.") => "",
        "changelog" => "",
        n if n.starts_with("changelog.") => "",
        "robots.txt" => "󰚩",
        ".gitattributes" | ".gitmodules" | ".gitignore" | ".gitconfig" => "",
        ".dockerignore" => "",
        ".npmrc" | "package.json" | "package-lock.json" => "",
        "yarn.lock" => "",
        "pnpm-lock.yaml" => "",
        "cargo.toml" | "cargo.lock" => "",
        "go.mod" | "go.sum" => "",
        "requirements.txt" | "pipfile" | "pipfile.lock" | "pyproject.toml" | "poetry.lock" => "",
        n if n.starts_with("tsconfig") && n.ends_with(".json") => "",
        n if n.starts_with("webpack") => "󰜫",
        ".env" => "",
        n if n.starts_with(".env.") => "",
        n if n.starts_with(".eslintrc") => "",
        ".editorconfig" => "",
        _ => ext_icon(&name),
    }
}

fn ext_icon(name: &str) -> &'static str {
    let ext = name.rsplit('.').next().unwrap_or_default();
    match ext {
        "py" => "",
        "js" => "",
        "ts" => "",
        "tsx" | "jsx" => "",
        "go" => "",
        "rs" => "",
        "rb" => "",
        "php" => "",
        "java" => "",
        "c" => "",
        "cpp" => "",
        "h" | "hpp" => "",
        "cs" => "󰌛",
        "swift" => "",
        "kt" | "kts" => "",
        "dart" => "",
        "lua" => "",
        "vim" => "",
        "sh" | "bash" | "zsh" | "fish" => "",
        "r" => "",
        "jl" => "",
        "scala" => "",
        "clj" | "cljs" => "",
        "ex" | "exs" => "",
        "erl" => "",
        "hs" => "",
        "ml" => "",
        "nim" => "",
        "zig" => "",
        "nix" => "",
        "pl" => "",
        "html" | "htm" => "",
        "css" => "",
        "scss" | "sass" => "",
        "less" => "",
        "vue" => "",
        "svelte" => "",
        "astro" => "",
        "graphql" | "gql" => "",
        "wasm" => "",
        "json" => "",
        "yaml" | "yml" => "",
        "toml" => "",
        "xml" => "󰗀",
        "ini" | "conf" | "config" | "properties" => "",
        "csv" => "",
        "tf" => "",
        "k8s" => "󱃾",
        "md" | "markdown" => "",
        "txt" | "rtf" => "󰈙",
        "pdf" => "",
        "doc" | "docx" => "󰈬",
        "xls" | "xlsx" => "󰈛",
        "ppt" | "pptx" => "󰈧",
        "tex" => "",
        "org" => "",
        "rst" => "",
        "log" => "󰌱",
        "png" | "jpg" | "jpeg" | "gif" | "ico" | "webp" | "bmp" | "tiff" => "󰸭",
        "svg" => "󰜡",
        "psd" => "",
        "ai" => "",
        "sketch" => "",
        "fig" => "",
        "mp4" | "avi" | "mkv" | "mov" | "webm" => "󰈫",
        "mp3" | "wav" | "flac" | "ogg" | "m4a" | "aac" => "󰈣",
        "zip" | "tar" | "gz" | "rar" | "7z" | "bz2" | "xz" | "tgz" => "",
        "deb" => "",
        "rpm" => "",
        "pkg" => "󰏗",
        "dmg" => "",
        "iso" => "󰗮",
        "jar" => "",
        "lock" => "",
        "gradle" => "",
        "maven" => "",
        "npm" | "package" => "",
        "yarn" => "",
        "pnpm" => "",
        "git" | "gitignore" | "gitmodules" | "gitattributes" | "gitconfig" => "",
        "compose" => "",
        "todo" => "",
        "sql" | "db" | "sqlite" | "sqlite3" | "mdb" => "",
        "pgsql" => "",
        "ttf" | "otf" | "woff" | "woff2" | "eot" => "",
        "env" | "envrc" => "",
        "prettierrc" | "babelrc" | "editorconfig" | "eslintrc" | "procfile" => "",
        "tsconfig" => "",
        "gemfile" | "rakefile" => "",
        "gruntfile" => "",
        "gulpfile" => "",
        "cmakelists" | "cmake" | "make" | "makefile" => "",
        _ => ICON_FILE,
    }
}
